blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("posts.urls"), name='posts')
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.HomeView, name="home"),
    path("<int:id>/", views.IndividualPostView, name="focus-post")
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    summary = models.TextField(default="No overview yet")

    def __str__(self):
        return self.title

posts/views.py
from django.shortcuts import render

from .models import Post

# Create your views here.
def HomeView(request):
    return render(request, "posts/home.html", {
        "posts" : Post.objects.all()
    })

def IndividualPostView(request, id):
    obj = Post.objects.get(id=id)
    return render(request, "posts/individual-post.html", {
        "individual_post" : obj,
    })

posts/templates/posts/home.html
{% extends "posts/layout.html" %} 

{% block title %}
        Sherbert Capital
{% endblock %}

{% block body %}
<h1>Blog</h1>
<div class = "item-card">
        {% for post in posts %}
                <div class = "blog-overview">
                        <a href = "{% url 'posts:focus-post' post.id %}" class = "blog-title-link">
                                <h2>{{post.title}}</h2>
                        </a>
                        <div class = "blog-summary">{{post.summary}}</div>
                </div>
        {% endfor %}
</div>
{% endblock %}

posts/templates/posts/individual-post.html
{% extends "posts/layout.html" %} 

{% block title %}
        {{individual_post.title}}
{% endblock %}

{% block body %}
    <h1>{{individual_post.title}}</h1>
    {{individual_post.body}}
{% endblock %}

posts/templates/posts/layout.html
{% load static %}
<!DOCTYPE html>

<html lang = "en">

<head>
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel = "stylesheet" href = "{% static 'posts/master.css' %}" >
</head>
        <div class = "top-nav">
            <div class= "navbar-brand-position">
                <a href = "{% url 'posts:home' %}" class = "navbar-brand" >Sherbert Capital</a>
            </div>
        </div>

    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>